kind: Service 
apiVersion: v1
metadata:
  name: cd-slides-example
spec:
  selector:
    app: cd-slides-example
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cd-slides-example
spec:
  selector:
    matchLabels:
      app: cd-slides-example
  template:
    metadata:
      labels:
        app: cd-slides-example
      annotations:
        kubernetes.io/change-cause: $IMAGE_NAME
    spec:
      containers:
        - name: cd-slides-example
          image: $IMAGE_NAME
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cd-slides-example
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: continuous-delivery-slides.cloudogu.com
      http:
        paths:
          - path: /
            backend:
              serviceName: cd-slides-example
              servicePort: 80